##################################
# Visualize the metaprograms across different batch features (tumor type and lab)
# Author: Kevin Johnson
# Date: 2026.04.13
##################################

library(tidyverse)
library(scales)

proj_dir    <- "/vast/palmer/pi/verhaak/kcj28/care_idh_mut"
fig_dir     <- file.path(proj_dir, "figures/")
source(file.path(proj_dir, "scripts/utils", "plot_theme.R"))
source(file.path(proj_dir, "scripts/utils", "PvsR-NMF-caremut.R"))

# Malignant metaprograms used in the current study
malignant_nmf_metaprograms <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/results/metaprograms/malignant_downsampled/malignant_nmf_metaprograms_out.RDS")

# The malignant_nmf_metaprograms object is a list containing the clusters (i.e. the NMF programs from which each MP was derived)
# and the MPs in tabular and in list form

# Use the simplified linker that contains mapping identifiers and key clinical information
meta_care <- read.table("/vast/palmer/pi/verhaak/kcj28/care_mut/data/metadata/caremut_sample_identifier_linker.txt", sep = "\t", row.names = 1, header = TRUE)
mp_res_df <- data.frame(
  Cluster = rep(names(malignant_nmf_metaprograms$clusters), sapply(malignant_nmf_metaprograms$clusters, length)),
  Sample = unlist(malignant_nmf_metaprograms$clusters)
)
mp_res_df$SampleID <- sapply(strsplit(mp_res_df$Sample, "_"), "[[", 1)
mp_res_df_annot <- mp_res_df %>% 
  inner_join(meta_care, "SampleID")

# Examine the distribution of clusters across tumor type and laboratory that generated the data 
table(mp_res_df_annot$Cluster, mp_res_df_annot$idh_codel_subtype)
table(mp_res_df_annot$Cluster, mp_res_df_annot$lab)

mp_res_df_annot_distinct <- mp_res_df_annot %>% 
  dplyr::select(Cluster, care_id:timepoint, sample_barcode:idh_codel_subtype) %>% 
  distinct()

mp_by_subtype <- mp_res_df_annot_distinct %>% 
  mutate(idh_codel_subtype = recode(idh_codel_subtype, `IDHmut-codel` = "IDH-O",
                                    `IDHmut-noncodel` = "IDH-A")) %>% 
  group_by(idh_codel_subtype, Cluster) %>% 
  summarise(counts = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = idh_codel_subtype, values_from = counts)

# Report any NAs as 0
mp_by_subtype[is.na(mp_by_subtype)] <- 0 

# Divide by the total number of tumor samples per tumor type
mp_by_subtype$IDH_A_freq <- mp_by_subtype$`IDH-A` / 45
mp_by_subtype$IDH_O_freq <- mp_by_subtype$`IDH-O` / 29

mp_by_subtype_long <- mp_by_subtype %>% 
  dplyr::select(Cluster, IDH_A_freq, IDH_O_freq) %>% 
  pivot_longer(cols=c(IDH_A_freq, IDH_O_freq), names_to = "subtype", values_to = "freq") %>% 
  mutate(Cluster = gsub("Cluster_", "MP_", Cluster))

mp_by_subtype_long$Cluster <- factor(mp_by_subtype_long$Cluster, levels=c("MP_1", "MP_2", "MP_3", "MP_4", "MP_5", "MP_6",
                                                                          "MP_7", "MP_8", "MP_9", "MP_10", "MP_11", "MP_12"))
mp_by_subtype_long$subtype <- factor(mp_by_subtype_long$subtype, levels=c("IDH_O_freq", "IDH_A_freq"))


# This represents a breakdown for malignant metaprograms where how many samples contributed to these groupings. For our analysis, we'll restrict to those detected in both tumor types,
# found across labs, and with genes not indicative of quality (e.g., ribosomal genes, antisense, or potentially contaminating RNA).
pdf(paste0(fig_dir, "caremut_metaprogram_sample_contribution_by_tumor_type.pdf"), width = 3.75, height = 3.75, useDingbats = FALSE)
ggplot(mp_by_subtype_long, aes(x=Cluster, y=freq*100, fill=subtype)) +
  geom_bar(position="dodge", stat="identity") +
  plot_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  scale_fill_manual(values=c("IDH_A_freq" = "#800074", 
                             "IDH_O_freq"="#298C8C"),
                    labels=c("IDH_A_freq" = "Astro.",
                             "IDH_O_freq" = "Oligo.")) +
  labs(x="Metaprogram", y="Percent contributing all samples\n(proportional to tumor type)", fill="Tumor type")
dev.off()

# All oligodendroglioma samples were generated by laboratory 3 (Verhaak lab). Need to examine only astrocytoma samples to inspect whether a metaprogram was detected across labs.
# Restrict to Astrocytoma samples.
mp_by_lab <- mp_res_df_annot_distinct %>% 
  filter(idh_codel_subtype=="IDHmut-noncodel") %>% 
  group_by(lab, Cluster) %>% 
  summarise(counts = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = lab, values_from = counts)

# Report any NAs as 0
mp_by_lab[is.na(mp_by_lab)] <- 0
# Divide by number of astrocytomas per lab. Oligodendrogliomas were only profiled by the Verhaak laboratory.
mp_by_lab$Iavarone_lab_freq <- mp_by_lab$`Iavarone lab` / 8
mp_by_lab$Suva_lab_freq <- mp_by_lab$`Suva lab` / 16
mp_by_lab$Verhaak_lab_freq <- mp_by_lab$`Verhaak lab` / 21

mp_by_lab_long <- mp_by_lab %>% 
  dplyr::select(Cluster, Iavarone_lab_freq:Verhaak_lab_freq) %>% 
  pivot_longer(cols=c( Iavarone_lab_freq:Verhaak_lab_freq), names_to = "lab", values_to = "freq") %>% 
  mutate(Cluster = gsub("Cluster_", "MP_", Cluster))

mp_by_lab_long$Cluster <- factor(mp_by_lab_long$Cluster, levels=c("MP_1", "MP_2", "MP_3", "MP_4", "MP_5", "MP_6",
                                                                  "MP_7", "MP_8", "MP_9", "MP_10", "MP_11", "MP_12"))

pdf(paste0(fig_dir, "caremut_metaprogram_astrocytoma_sample_contribution_by_lab.pdf"), width = 4, height = 3.75, useDingbats = FALSE)
ggplot(mp_by_lab_long, aes(x=Cluster, y=freq*100, fill=lab)) +
  geom_bar(position="dodge", stat="identity") +
  plot_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  scale_fill_manual(values =c( "Iavarone_lab_freq"= "#7570b3", "Suva_lab_freq"="#d95f02", "Verhaak_lab_freq"="#1b9e77"),
                    labels =c("Iavarone_lab_freq"="Lab 1 (n=8)", "Verhaak_lab_freq"="Lab 3 (n=21)", "Suva_lab_freq"="Lab2 (n=16)"),
                    name="Astro. (lab)") +
  labs(x="Metaprogram", y="Percent contributing astrocytoma samples\n(proportional to lab)") 
dev.off()

# MP6 was detected in Verhaak laboratory oligodendroglioma samples and also both other labs for astrocytomas.
# MP7 was assoc. with antisense genes and the remaining were detected in either only one tumor type, mainly by one lab, etc. MP7-12 were not considered for cell state identification
table(mp_res_df_annot_distinct$Cluster, mp_res_df_annot_distinct$lab)

mp_res_df_annot_filt <- mp_res_df_annot %>% 
  filter(Cluster%in%c("Cluster_1", "Cluster_2", "Cluster_3", "Cluster_4", "Cluster_5", "Cluster_6", "Cluster_7", "Cluster_8", "Cluster_9", "Cluster_10", "Cluster_11", "Cluster_12")) %>% 
  dplyr::select(Cluster:Sample, SampleID)

nmf_intersect_KEEP <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/results/metaprograms/malignant_downsampled/nmf_intersect_KEEP.RDS")
inds_new <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/results/metaprograms/malignant_downsampled/inds_new.RDS")

tmp <- nmf_intersect_KEEP[inds_new,inds_new]
tmp_filtered <- tmp[rownames(tmp)%in%mp_res_df_annot_filt$Sample, colnames(tmp)%in%mp_res_df_annot_filt$Sample]
nmf_intersect_meltI_NEW_compare <- reshape2::melt(tmp_filtered)


nmf_intersect_meltI_NEW <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/results/metaprograms/malignant_downsampled/nmf_intersect_meltI_NEW.RDS")
nmf_intersect_meltI_NEW_annot <- nmf_intersect_meltI_NEW %>%
  filter(Var1%in%mp_res_df_annot_filt$Sample, Var2%in%mp_res_df_annot_filt$Sample)

all(as.character(nmf_intersect_meltI_NEW_compare$Var1)==nmf_intersect_meltI_NEW_annot$Var1)
all(as.character(nmf_intersect_meltI_NEW_compare$Var2)==nmf_intersect_meltI_NEW_annot$Var2)

# Full NMF metaprogram heatmap. We don't report on the other NMF programs beyond those identified in MP1-MP12
p <- ggplot(data = nmf_intersect_meltI_NEW, aes(x=Var1, y=Var2, fill=100*value/(100-value), color=100*value/(100-value))) + 
  geom_tile() + 
  scale_color_gradient2(limits=c(2,25), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 13.5, oob=squish, name="Similarity\n(Jaccard index)") +
  scale_fill_gradient2(limits=c(2,25), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 13.5, oob=squish, name="Similarity\n(Jaccard index)")  +
  theme( axis.ticks = element_blank(), panel.border = element_rect(fill=F), panel.background = element_blank(),  axis.line = element_blank(), axis.text = element_text(size = 11), 
         axis.title = element_text(size = 12), legend.title = element_text(size=11), legend.text = element_text(size = 10), legend.text.align = 0.5, legend.justification = "bottom") + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) + 
  theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) + 
  guides(fill = guide_colourbar(barheight = 4, barwidth = 1))

# Heatmap restricted to only those where we derived malignant metaprograms for the study. (386)
p2 <- ggplot(data = nmf_intersect_meltI_NEW_annot, aes(x=Var1, y=Var2, fill=100*value/(100-value), color=100*value/(100-value))) + 
  geom_tile() + 
  scale_color_gradient2(limits=c(2,25), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 13.5, oob=squish, name="Similarity\n(Jaccard index)") +
  scale_fill_gradient2(limits=c(2,25), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 13.5, oob=squish, name="Similarity\n(Jaccard index)")  +
  theme( axis.ticks = element_blank(), panel.border = element_rect(fill=F), panel.background = element_blank(),  axis.line = element_blank(), axis.text = element_text(size = 14), 
         axis.title = element_text(size = 14), legend.title = element_text(size=14), legend.text = element_text(size = 14), legend.text.align = 0.5, legend.justification = "bottom") + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) + 
  theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) + 
  guides(fill = guide_colourbar(barheight = 4, barwidth = 1))

# Provide some annotation to the NMF program can have an annotation bar
rownames(meta_care) <- meta_care$SampleID

nmf_annot_type_tumor  <- data.frame("sample"=sub("\\_.*", "", colnames(tmp_filtered)))
nmf_annot_type_tumor$idh_codel_subtype <- meta_care$idh_codel_subtype[match(nmf_annot_type_tumor$sample, rownames(meta_care))]
nmf_annot_type_tumor$idh_codel_subtype <- factor(nmf_annot_type_tumor$idh_codel_subtype, levels=sort(unique(nmf_annot_type_tumor$idh_codel_subtype)))
nmf_annot_type_tumor$timepoint <- meta_care$timepoint[match(nmf_annot_type_tumor$sample, rownames(meta_care))]
nmf_annot_type_tumor$timepoint <- factor(nmf_annot_type_tumor$timepoint, levels=sort(unique(nmf_annot_type_tumor$timepoint)))
nmf_annot_type_tumor$lab <- meta_care$lab[match(nmf_annot_type_tumor$sample, rownames(meta_care))]
nmf_annot_type_tumor$lab <- factor(nmf_annot_type_tumor$lab, levels=sort(unique(nmf_annot_type_tumor$lab)))


p_annotation_tumor_type <- ggplot(nmf_annot_type_tumor, aes(y="", x=1:nrow(nmf_annot_type_tumor), fill=idh_codel_subtype, color=idh_codel_subtype)) +
  geom_tile() +
  scale_color_manual(values =c( "IDHmut-codel"= "#298C8C", "IDHmut-noncodel"="#800074"), name="") +
  scale_fill_manual(values =c( "IDHmut-codel"= "#298C8C", "IDHmut-noncodel"="#800074"), name="") +                                                    
  theme(axis.ticks = element_blank(), panel.background = element_rect(fill = "white"),  axis.line = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 14),  axis.title = element_text(size=14),  legend.text.align = 0, legend.key.size = unit(0.4, "cm"), legend.key=element_blank(), legend.position=c(1.3,-4), plot.margin = unit(c(0.5,3,-0.6,0.5), "cm")) +
  scale_x_continuous(expand = c(0,0)) +
  labs(x="", y="") +
  guides(fill = "none", color="none")


# Combine plots
pdf(paste0(fig_dir, "similarity_heatmap_mp_care_mut_annot_all_malignant_12clusters.pdf"), width = 7, height = 5, onefile=FALSE)
egg::ggarrange(p_annotation_tumor_type, p2, nrow = 2, heights = c(0.5, 8))
dev.off()

pdf(paste0(fig_dir, "similarity_heatmap_mp_care_mut_annot_all_malignant_12clusters.png"), width = 7, height = 5, onefile=FALSE)
egg::ggarrange(p_annotation_tumor_type, p2, nrow = 2, heights = c(0.5, 8))
dev.off()
