#################################
## Compare the gene overlap between CAREmut NMF metaprograms and other gene lists
## Author: Kevin Johnson
## Updated:2026.04.03
#################################


library(RColorBrewer)
library(viridis)
library(tidyverse)
library(scales)

proj_dir    <- "/vast/palmer/pi/verhaak/kcj28/care_idh_mut"
setwd(proj_dir)

# Set a few plotting defaults
custom_magma <- c(colorRampPalette(c("white", rev(magma(323, begin = 0.15))[1]))(10), rev(magma(323, begin = 0.18)))
source("scripts/utils/plot_theme.R")

# CARE IDH-mutant malignant metaprograms for n = 74 samples.
care_mut_mps <- read.table("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/results/metaprograms/care_mut_selected_malignant_metaprograms.csv", sep = ",", header = T, row.names = 1)

# CARE-WT metaprograms generated for n = 121 samples. snRNA data generated by the same labs.
care_wt_mps <- read.delim("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/data/misc/carewt_malignant_metaprograms.txt", sep = "\t", header = T)
colnames(care_wt_mps) <- gsub("MP_", "CARE_IDHwt_MP", colnames(care_wt_mps))

# Blanco-Carmona et al Cell Reports Medicine 2023 for mixed oligodendroglioma and astrocytoma for the same labs - snRNA data.
blanco_mps <- read.delim("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/data/misc/blancocarmona_snrna_n26_malignant_metaprograms.csv", sep = ",", row.names = 1, header = T)
colnames(blanco_mps) <- paste0(colnames(blanco_mps), "_Blanco-Carmona")

# CGGA single cell* RNA data across IDH-mutant astrocytoma and oligodendroglioma.
cgga_mps <- read.delim("/vast/palmer/pi/verhaak/kcj28/care_idh_mut/data/misc/cgga_scrna_n46_malignant_metaprograms.csv", sep = ",", row.names = 1, header = T)
colnames(cgga_mps) <- paste0(colnames(cgga_mps), "_CGGA")

# Calculate overlaps for CAREmut and CARE_IDHwt. Remove quality associated metaprograms. Reorder so that it aligns with how the IDH-mutant MPs are presented.
care_wt_mps_filt <- care_wt_mps[, c(4,5,6,8,2,7,3,9,10,13,14,15)]
colnames(care_wt_mps_filt)  <- gsub("_MP[0-9]_|_MP[0-9][0-9]_", "_MP_", colnames(care_wt_mps_filt))

# Look at the gene overlap across the different metaprograms from IDH-mutant and IDH-wildtype from the CARE consortium.
intersect_matrix_wt <- apply(care_mut_mps, 2, function(x) {
  sapply(care_wt_mps_filt, function(y) length(intersect(x, y)))
})
intersect_matrix_melt_wt <- reshape2::melt(intersect_matrix_wt) 
intersect_matrix_melt_wt$comparison <- "IDHwt (n=121)"


# Blanco-Carmona
# MP1 - AC; MP2 = OPC/OC-1, MP3 = CC; MP4 = OPC/OC-2; MP5 = RPL; MP6 = NPC;
blanco_mps_filt <- blanco_mps[,c(1,4,2,6,3)]
colnames(blanco_mps_filt) <- c("BlancoCarmona_MP_AC", "BlancoCarmona_MP_MES", "BlancoCarmona_MP_OPC", "BlancoCarmona_MP_NPC/Mix", "BlancoCarmona_MP_CC")


intersect_matrix_blanco <- apply(care_mut_mps, 2, function(x) {
  sapply(blanco_mps_filt, function(y) length(intersect(x, y)))
})

intersect_matrix_melt_blanco <- reshape2::melt(intersect_matrix_blanco) 
intersect_matrix_melt_blanco$comparison <- "Blanco-Carmona IDHmut (n=26)"

# CGGA - select main metaprograms
# MP1 - AC; MP2 = OPC/OC-1, MP3 = CC; MP4 = OPC/OC-2; MP5 = RPL; MP6 = NPC; MP7 = Stress, MP8 = stress, MP9 = Protein folding/OxPhos, MP10 = hypoxia
cgga_mps_filt <- cgga_mps[,c(1,2,4,6, 3, 7, 8, 10)]
colnames(cgga_mps_filt) <- c("CGGA_MP_AC", "CGGA_MP_OPC",  "CGGA_MP_OC", "CGGA_MP_NPC", "CGGA_MP_CC", "CGGA_MP_Stress1", "CGGA_MP_Stress2", "CGGA_MP_Hypoxia")
intersect_matrix_cgga <- apply(care_mut_mps, 2, function(x) {
  sapply(cgga_mps_filt, function(y) length(intersect(x, y)))
})
intersect_matrix_melt_cgga <- reshape2::melt(intersect_matrix_cgga) 
intersect_matrix_melt_cgga$comparison <- "CGGA IDHmut (n=46)"

# Combine all for the same plot
intersect_matrix_melt_comb <- bind_rows(intersect_matrix_melt_wt,
                                        intersect_matrix_melt_blanco,
                                        intersect_matrix_melt_cgga)

intersect_matrix_melt_comb <- intersect_matrix_melt_comb %>% 
  mutate(comparison = recode(comparison, `IDHwt (n=121)` = "IDHwt snRNA",
                             `CGGA IDHmut (n=46)` = "IDHmut scRNA",
                             `Blanco-Carmona IDHmut (n=26)` = "IDHmut snRNA"))

pdf("figures/edf4g_malignant_mp_comparisons.pdf", width = 4.25, height = 5, useDingbats = FALSE, bg = "transparent")
ggplot(data = intersect_matrix_melt_comb, aes(y=Var1, x=Var2, fill=(value/50)*100, color=(value/50)*100)) + 
  geom_tile() + 
  scale_color_gradient2(limits=c(0,100), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 50, oob=squish, name="Similarity %\n(Jaccard index)") +
  scale_fill_gradient2(limits=c(0,100), low=custom_magma[1:111],  mid =custom_magma[112:222], high = custom_magma[223:333], midpoint = 50, oob=squish, name="Similarity %\n(Jaccard index)")  +
  guides(fill = guide_colourbar(barheight = 4, barwidth = 1)) +
  facet_grid(comparison~.,  scales = "free_y", space="free") +
  plot_theme +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="CARE IDHmut metaprograms", y="Metaprograms derived from each study")
dev.off()


### END ###