##################################
# 10x snRNAseq analysis of preprocessing approaches for CARE-IDH-mutant astrocytomas
# Author: Kevin Johnson
# Date Updated: 2026.03.17
##################################

library(tidyverse)
library(RColorBrewer)
library(viridis)
library(Seurat)
library(harmony)
library(Matrix)
library(ggpubr)
library(openxlsx)
library(DoubletFinder)

## Specify directories that have the count matrices. These are spread out across a few directories because they were processed at different times or by different labs.
in_data_dir_1 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/internal/batch1"
in_data_dir_2 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/internal/batch2"
in_data_dir_3 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/external"

# Define where figures and results will be stored
fig_dir <- "/vast/palmer/pi/verhaak/kcj28/care_mut/results/figures/rna/"
out_data_dir <- "/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna"
setwd("/vast/palmer/pi/verhaak/kcj28/care_mut/results/")

# Load in the master mapping file to utilize the different sample identifiers from the verhaak lab's data
map_df <- read.table("/vast/palmer/pi/verhaak/shared/monitor/metadata/glass_sn_bulk_master_mapping_file_20230729.txt", sep = "\t", header = T)
# Data generated by other groups (Suva + Iavarone labs)
map_df_external <- read.table("/vast/palmer/pi/verhaak/kcj28/care_mut/data/metadata/care_mut_external_dna_sn_linker_20230718.txt", sep = "\t", header = T)
map_df_external <- map_df_external %>% 
  mutate(file_path = ifelse(processed_by=="Iavarone lab", paste0("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/", avishay_id),
                            paste0("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/", data_name))) %>% 
  mutate(dir_name = ifelse(processed_by=="Iavarone lab",avishay_id, data_name))
# Needed to change this value since the data was coded differently for the directory versus metadata sheet.
map_df_external$dir_name[map_df_external$avishay_id=="P44T1"] <- "N1204557493"

# Are all files accounted for? Yes. Avishay also shared "COLUMBIA109695861", but that was already shared as P19T2 by Fulvio.
care_mut_dirs <- list.files("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/")
sum(map_df_external$dir_name%in%care_mut_dirs)
care_mut_dirs[!care_mut_dirs%in%map_df_external$dir_name]

# This should be empty
map_df_external %>% 
  filter(!dir_name%in%care_mut_dirs)

# Restrict this analysis to the IDHmut samples generated by our own lab - 23 patients, 51 samples. 5 samples with 3 time points.
map_df_mut <- map_df %>% 
  filter(idh_codel_subtype!="IDHwt") %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  mutate(patient_id = sapply(strsplit(multiome_id, "-|_"), "[[", 1))

# Create metadata file that is standard across patients
map_df_mut_filt <- map_df_mut %>% 
  mutate(lab = "Verhaak lab") %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  dplyr::select(SampleID = multiome_id, sample_barcode, case_barcode, lab, idh_codel_subtype)

map_df_external_filt <- map_df_external %>% 
  # All data shared by external groups were confirmed IDHmut-noncodel
  mutate(idh_codel_subtype = "IDHmut-noncodel") %>% 
  mutate(sample_barcode = substr(aliquot_barcode, 1, 15)) %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  dplyr::select(SampleID = dir_name, sample_barcode, case_barcode, lab = processed_by, idh_codel_subtype)

md_to_add <- bind_rows(map_df_mut_filt, map_df_external_filt)

#########################################################################################
#### Load in the 10x data on which cells were filtered and DoubletFinder was run independently on each sample - 
#### see scripts/preprocess/care_10x_preprocess_snrna.R
#########################################################################################
seurat_obj_singlets <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/caremut_seuratobj_filt_singlets_20230728.RDS")

# Identify columns starting with "pANN" in the metadata and remove them for cleaning purposes. These were added by DoubletFinder.
columns_to_remove <- grep("^pANN", colnames(seurat_obj_singlets@meta.data), value = TRUE)
seurat_obj_singlets@meta.data <- seurat_obj_singlets@meta.data[, !colnames(seurat_obj_singlets@meta.data) %in% columns_to_remove]

# Quick sanity checks for SampleIDs
test_md <- seurat_obj_singlets@meta.data
test_md$sample_id_new <- sub("-[ACGT]+-\\d+$", "", rownames(test_md))
all(test_md$sample_id_new==test_md$SampleID)
table(test_md$sample_id_new)==table(test_md$SampleID)

# Use a list of differentially expressed genes for CARE IDHwt glioma (snRNA) so that we can later score cells, but restrict to the genes in this dataset.
celltype_markers <- readRDS("/vast/palmer/pi/verhaak/kcj28/genelists/celltype_markers.RDS")

# Select the top 100 genes in terms of fold-change for each cell type.
selected_genes <- celltype_markers %>%
  filter(CellType %in% c("Malignant", "Astrocyte", "Excitatory neuron", "Inhibitory neuron", "OPC", "Oligodendrocyte", "Endothel", "Pericyte", "Macrophage", "Tcell", "Bcell")) %>%
  group_by(CellType) %>%
  arrange(CellType, desc(log2FC)) %>%
  top_n(100, log2FC)

all.genes <- rownames(seurat_obj_singlets)
selected_genes_vector <- unique(selected_genes$Gene[selected_genes$Gene%in%all.genes])
# Check to make sure that each gene is only being used once as some marker genes overlap.
n_distinct(selected_genes_vector)==length(selected_genes_vector)

# Convert this to a list so that we can later use Seurat's AddModuleScore's functionality
selected_genes_filt <- selected_genes %>% 
  filter(Gene%in%selected_genes_vector, !CellType%in%c("Unresolved", "Other normal")) %>% 
  as.data.frame()
cell_type_markers <- split(selected_genes_filt, selected_genes_filt$CellType)
cell_type_markers_list <- lapply(cell_type_markers, function(x) as.character(x$Gene))

# Determine the length of each element in the list
lengths <- lengths(cell_type_markers_list)

# Subset the list to exclude elements with length 0
cell_type_markers_list <- cell_type_markers_list[lengths > 0]

# Add the metadata of case_barcode and processing_lab - if desired.
seurat_md <- seurat_obj_singlets@meta.data
seurat_md$CellID <- rownames(seurat_md)
add_data <- seurat_md %>% 
  left_join(md_to_add, by="SampleID")

all(seurat_md$CellID==row.names(seurat_obj_singlets[[]]))

row.names(add_data) <- row.names(seurat_obj_singlets[[]])
seurat_obj_singlets <- AddMetaData(seurat_obj_singlets, metadata = add_data)

# Load in the metadata that was used in the pre-revision analysis to assess.
caremut_md <- read.table("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/care_mut_cleaned_snrna_metadata_n75_20240212.txt", sep = "\t", row.names = 1, header = TRUE)
caremut_md_filtered <- caremut_md %>% 
  dplyr::select(CellID, seurat_final_clusters_og = seurat_final_clusters, CellType_initial_og = CellType_initial, CellType_infercnv_og = CellType_infercnv, CellType_final_og = CellType_final,
                predicted.class, predicted.subclass, scna_burden, malignant_cor, care_id, sample_barcode)

# Two samples with a lot of mural cells: CARE-MD-MD04-R1 and GLSS-LX-0178-R2
mural <- caremut_md_filtered %>% 
  filter(CellType_final_og=="Mural")
table(mural$sample_barcode)[table(mural$sample_barcode) > 50]

seurat_md_part2 <- seurat_obj_singlets@meta.data

add_data_part2 <- seurat_md_part2 %>% 
  left_join(caremut_md_filtered, by="CellID")
all(add_data_part2$CellID==row.names(seurat_obj_singlets[[]]))

row.names(add_data_part2) <- row.names(seurat_obj_singlets[[]])

seurat_obj_singlets <- AddMetaData(seurat_obj_singlets, metadata = add_data_part2)

all(rownames(seurat_obj_singlets@meta.data)==Cells(seurat_obj_singlets))

#########################################################################################
##### Preprocess with Harmony - noncodel / astrocytoma
#########################################################################################
# Subset the data to only those non-codel tumors
seurat_obj_singlets_noncodel <- subset(seurat_obj_singlets, idh_codel_subtype=="IDHmut-noncodel")

# Clear out some space:
rm(seurat_obj_singlets)
gc()

# There are 45 distinct tumors (8 processed by the Iavarone lab, 16 by the Suva lab, 21 by the Verhaak lab)
n_distinct(seurat_obj_singlets_noncodel$SampleID)
table(seurat_obj_singlets_noncodel$SampleID, seurat_obj_singlets_noncodel$lab)


### Harmony batch correction **with set.seed(42)**
astro_sobj_all_harmony <- NormalizeData(seurat_obj_singlets_noncodel, normalization.method = "LogNormalize", scale.factor = 10000)
astro_sobj_all_harmony <- FindVariableFeatures(astro_sobj_all_harmony, selection.method = "vst", nfeatures = 5000)
# By default only variable features are scaled.
astro_sobj_all_harmony <- ScaleData(astro_sobj_all_harmony)
astro_sobj_all_harmony <- RunPCA(astro_sobj_all_harmony, features = VariableFeatures(object = astro_sobj_all_harmony), npcs=50, seed.use = 42)
set.seed(42)
astro_sobj_all_harmony <- RunHarmony(astro_sobj_all_harmony, group.by.vars = c("case_barcode", "lab"), dims.use = 1:30)
astro_sobj_all_harmony <- FindNeighbors(astro_sobj_all_harmony, reduction = "harmony", dims = 1:20) 
# default: random.seed = 0
astro_sobj_all_harmony <- FindClusters(astro_sobj_all_harmony, resolution = 0.6, reduction = "harmony", random.seed = 0) 
#  default: seed.use = 42 
astro_sobj_all_harmony <- RunUMAP(astro_sobj_all_harmony, reduction = "harmony", dims = 1:20, min.dist = 0.2, n.neighbors = 40, seed.use = 42)

DimPlot(astro_sobj_all_harmony, label = TRUE, group.by = "RNA_snn_res.0.6",repel = TRUE,  pt.size = 1) 
DimPlot(astro_sobj_all_harmony, label = TRUE, group.by = "CellType_final_og",repel = TRUE,  pt.size = 1) 

# Create a UMAP with the paper's annotation to quickly see how they align.
harmony_42_umap_plot <- DimPlot(astro_sobj_all_harmony, group.by = "CellType_final_og",
                              cols =  c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", 
                                        "Astrocyte" = "#BFBADA", "ExcNeuron" = "#BC80BD", 
                                        "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", "Unresolved" = "gray70"),
                              # Manually add point size for larger number of cells
                              pt.size = 1) + ggtitle(" Harmony - set.seed(42)")
ggsave(paste0(fig_dir, "astrocytoma_harmony_setseed42_umap_20260314.png"), harmony_42_umap_plot, width = 7, height = 4, dpi = 300)

# Is it the same as the last time we ran it? Yes, clusters remain the same.
astro_sobj_all_harmony_md <- astro_sobj_all_harmony@meta.data
astro_sobj_all_harmony_md_old <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_mut/data/sanity_checks/astrocytoma_preprocessing_metadata_harmony_seed42_pipeline.RDS")
all(rownames(astro_sobj_all_harmony_md)==rownames(astro_sobj_all_harmony_md_old))
all(astro_sobj_all_harmony_md$RNA_snn_res.0.6==astro_sobj_all_harmony_md_old$RNA_snn_res.0.6)


# We defined a set of cell type marker genes from IDH-WT glioblastoma (above). Score each cell for these signatures to help identify clusters in this dataset.
astro_sobj_all_harmony <- AddModuleScore(astro_sobj_all_harmony,
                                                       features = cell_type_markers_list,
                                                       name=names(cell_type_markers_list))

sig_cols <- c("Malignant1", "Oligodendrocyte2", "Macrophage3", "Astrocyte4", 
              "Excitatory.neuron5", "Inhibitory.neuron6", "Endothel7", 
              "Pericyte8", "Tcell9", "Bcell10", "OPC11")
astro_sobj_all_harmony@meta.data <- astro_sobj_all_harmony@meta.data %>%
  rename_with(~ sub("\\d+$", "_sig", .x), all_of(sig_cols))

sig_cols_added <- c("Malignant_sig", "Oligodendrocyte_sig", "Macrophage_sig", 
              "Astrocyte_sig", "Excitatory.neuron_sig", "Inhibitory.neuron_sig", 
              "Endothel_sig", "Pericyte_sig", "Tcell_sig", "Bcell_sig", "OPC_sig")

# Find the column name with the highest score per cell. These align with what's expected.
astro_sobj_all_harmony@meta.data <- astro_sobj_all_harmony@meta.data %>%
  mutate(CellType_Sig = apply(across(all_of(sig_cols_added)), 1, function(x) {
    sig_cols_added[which.max(x)]
  }))
DimPlot(astro_sobj_all_harmony, label = TRUE, group.by = "CellType_Sig",repel = TRUE,  pt.size = 1) 

# Plot these individual signatures to identify any potential residual doublet populations.
# Malignant+Macrophage+Oligodendrocyte are the most abundant and DoubletFinder doesn't capture these populations very well.
FeaturePlot(astro_sobj_all_harmony,  features = "Malignant_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Oligodendrocyte_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Macrophage_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Astrocyte_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Excitatory.neuron_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Inhibitory.neuron_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Endothel_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Pericyte_sig",  pt.size = 1) 
# Lymphocyte signal
FeaturePlot(astro_sobj_all_harmony,  features = "Tcell_sig",  pt.size = 1) 
FeaturePlot(astro_sobj_all_harmony,  features = "Bcell_sig",  pt.size = 1) 

# Add the "C" prefix to make it easier to look through the clusters
# astro_sobj_all_harmony@meta.data$RNA_snn_res.0.6 <- paste0("C", astro_sobj_all_harmony@meta.data$RNA_snn_res.0.6)
# Idents(astro_sobj_all_harmony) <- "RNA_snn_res.0.6"
head(astro_sobj_all_harmony@active.ident)
# Find the markers for these high-level clusters
#all_markers <- FindAllMarkers(astro_sobj_all_harmony, 
#                              only.pos = TRUE,      
#                              min.pct = 0.5,       
#                              logfc.threshold = 1)

# saveRDS(all_markers, "/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/preprocessing_publication/astro_sobj_all_harmony_clusters_markers.RDS")

# Filter for most meaningful cluster markers
top_markers <- all_markers %>%
  filter(p_val_adj < 0.05) %>%
  group_by(cluster) %>%
  slice_max(avg_log2FC, n = 5) 

# Get a feeling for which clusters may be problematic and save
cells_per_cluster <- astro_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, .drop = FALSE) %>% 
  summarise(counts = n()) %>% 
  ungroup()

cluster_composition_sample <- astro_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, sample_barcode, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

high_percentage_clusters <- cluster_composition_sample %>% 
  filter(percentage > 50)

tmp <- cluster_composition_sample %>% 
  filter(sample_barcode=="GLSS-LX-0178-R1")

# It seems like we can drop C19 and C25 due to past evaluations for this sample/case. Conservative option is to remove.
c19 <- cluster_composition_sample %>% 
  filter(RNA_snn_res.0.6%in%c("19")) %>% 
  arrange(desc(n))
sum(c19$percentage)

c25 <- cluster_composition_sample %>% 
  filter(RNA_snn_res.0.6%in%c("25")) %>% 
  arrange(desc(n))

suspicious_small_clusters <- cluster_composition_sample %>% 
  filter(RNA_snn_res.0.6%in%c("33", "34", "35")) %>% 
  arrange(desc(n))

# Examine the cluster composition based on our first pass classification
cluster_composition <- astro_sobj_all_harmony@meta.data %>%
  mutate(CellType_final_og = as.character(CellType_final_og)) %>%  # ensure NAs aren't dropped as factor levels
  group_by(RNA_snn_res.0.6, CellType_final_og, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

cell_type_colors <- c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", "Astrocyte" = "#BFBADA", 
                      "ExcNeuron" = "#BC80BD", "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", 
                      "Unresolved" = "gray70", "NA" = "black")

ggplot(cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                y = percentage, 
                                fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

ggplot(cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                y = n, 
                                fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")


# Examine the clusters by SampleIDs.
suspicious_clusters_by_sample_freq <- astro_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, SampleID) %>% 
  summarise(counts = n()) %>% 
  mutate(freq = counts / sum(counts)) %>% 
  ungroup() %>% 
  filter(RNA_snn_res.0.6%in%c("13", "18", "19", "25", "33", "34", "35"))

# Cluster 13: Malignant+Macrophage
top_markers %>% filter(cluster=="C13")
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "13"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)

# Cluster 18: Oligodendrocyte+Malignant
top_markers %>% filter(cluster=="C18")
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "18"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
# Cluster 19+25: An unsual set of cells from MD05. Previously discarded due to unusual infercnv profile and neuronal genes that don't align with the excitatory neurons.
# C19 and C25 are problematic clusters that I am removing for the following reasons:
# 1. The marker genes for this cluster are neuronal, but they do not cluster with the neurons unlike every other sample suggesting that they might be malignant
# 2. When I performed clustering using both IDH-O and IDH-A tumors, these cells clustered with neurons suggesting that they might be neuronal
# 3. The cluster is mostly composed of a single case (CARE-MD-MD05), which has a low purity tumor not suggestive of a high malignant fraction in snRNA data
# 4. The infercnv result was unusual. There was a group of malignant cells with CNVs that fit the canonical IDH-A (Chr7/8), but another set of cells in
# C18 that possessed CNV signals distinct from the stereotypical neuron signal but also did not align with the genetics from the recurrent tumor.
top_markers %>% filter(cluster=="C19")
top_markers %>% filter(cluster=="C25")
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "19"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "25"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)

# C33-C34 were largely not part of the original analysis
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "33"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "34"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "35"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
DimPlot(astro_sobj_all_harmony, cells.highlight = WhichCells(astro_sobj_all_harmony, idents = "11"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)


clusters_of_interest <- c("13", "18", "19", "25", "33", "34", "35")
VlnPlot(subset(astro_sobj_all_harmony, idents = clusters_of_interest),
        features = "Malignant_sig",
        pt.size = 0)

VlnPlot(subset(astro_sobj_all_harmony, idents = clusters_of_interest),
        features = "Oligodendrocyte_sig",
        pt.size = 0)

VlnPlot(subset(astro_sobj_all_harmony, idents = clusters_of_interest),
        features = "Macrophage_sig",
        pt.size = 0)

VlnPlot(subset(astro_sobj_all_harmony, idents = clusters_of_interest),
        features = "Pericyte_sig",
        pt.size = 0)



# Where do these residual doublets map on the UMAP:
potential_doublets <- rownames(astro_sobj_all_harmony@meta.data)[astro_sobj_all_harmony@meta.data$RNA_snn_res.0.6%in%c("13", "18", "19", "25", "33", "34", "35")]
DimPlot(astro_sobj_all_harmony, label=T, cells.highlight = list(potential_doublets), cols.highlight = c("darkblue"), cols= "grey", pt.size = 1,  raster = FALSE)


pre_removal_cell_num <- dim(astro_sobj_all_harmony)[2]
Idents(astro_sobj_all_harmony) <- "RNA_snn_res.0.6"
# C13 = Myeloid+Malignant 
# C18 = Oligodendrocyte+Malignant, C18 = Oligodendrocyte+Myeloid 
# C19/C25 = Neuronal/Malignant. No clear evidnce for true malignant cells based on CNV and repeated clustering.
# C33 + C34 = Maps across mural, malignant, myeloid (Driven by two samples) while C35 is a single sample cluster with only a small amount of cells.
# Remove residual doublets:
astro_sobj_all_harmony_cleaned <- subset(astro_sobj_all_harmony, idents = c(13, 18, 19, 25, 33, 34, 35), invert = TRUE)
dropped_cells <- pre_removal_cell_num-dim(astro_sobj_all_harmony_cleaned)[2]
sprintf("%s cells were removed due to ambiguous clusters.", dropped_cells) # 7,114 cells 

# Plot cleaned UMAP
DimPlot(astro_sobj_all_harmony_cleaned, label = TRUE, repel = TRUE, pt.size = 1) + NoLegend()


clean_cluster_composition <- astro_sobj_all_harmony_cleaned@meta.data %>%
  mutate(CellType_final_og = as.character(CellType_final_og)) %>%  # ensure NAs aren't dropped as factor levels
  group_by(RNA_snn_res.0.6, CellType_final_og, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

ggplot(clean_cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                y = percentage, 
                                fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")


# Provide a celltype assignment based on these initial 
astro_sobj_all_harmony_cleaned$CellType_clusters <- paste0("C", as.character(astro_sobj_all_harmony_cleaned$RNA_snn_res.0.6))
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C4"), "Oligodendrocyte", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C2", "C24", "C26", "C28", "C29"),"Myeloid", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C21"),"Lymphocyte", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C11"),"ExcNeuron", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C14"),"InhNeuron", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C10"),"Mural", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C15"),"Endothelial", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C9"),"Astrocyte", astro_sobj_all_harmony_cleaned$CellType_clusters)
astro_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(astro_sobj_all_harmony_cleaned$CellType_clusters %in% c("C0", "C1", "C3", "C5","C6","C7", "C8", "C12", "C16", "C17","C20","C22", "C23", "C27", "C30", "C31", "C32", "C36", "C37"),"Malignant", astro_sobj_all_harmony_cleaned$CellType_clusters)

png(paste0(fig_dir, "caremut_snrna_post_dfinder_cleaned_umap_celltype_20260317.png"), width=10, height=8, res=300, units='in')
DimPlot(astro_sobj_all_harmony_cleaned, group.by = "CellType_clusters", label = TRUE, repel = TRUE, 
        cols =  c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", 
                  "Astrocyte" = "#BFBADA", "ExcNeuron" = "#BC80BD", 
                  "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7"),
        pt.size = 1) +
  labs(x="UMAP1", y="UMAP2",color="Cell type")
dev.off()

table(astro_sobj_all_harmony_cleaned$CellType_initial_og, astro_sobj_all_harmony_cleaned$CellType_clusters)

# Approximate match percentage across gene expression clusters (99.4%).
sum(astro_sobj_all_harmony_cleaned$CellType_initial_og==astro_sobj_all_harmony_cleaned$CellType_clusters, na.rm = TRUE)/length(astro_sobj_all_harmony_cleaned$CellType_clusters)

# CARE-MD-MD04-R1, GLSS-LX-0178-R1, GLSS-LX-0178-R2 are the samples with the biggest mismatch.
expression_mismatch <- astro_sobj_all_harmony_cleaned@meta.data %>% 
  filter(CellType_initial_og!=CellType_clusters) %>% 
  dplyr::select(SampleID, sample_barcode, CellType_initial_og, CellType_clusters, CellType_final_og, RNA_snn_res.0.6)

expression_mismatch %>% filter(CellType_clusters=="Myeloid")

#########################################################################################
######### Write out CARE-mut metadata file containing cell state identifier
#########################################################################################
# Set the metadata and create a CellID
caremut_md_out <- astro_sobj_all_harmony_cleaned@meta.data

## Write out metadata table
write.table(caremut_md_out, 
            file = paste0(out_data_dir, "/astrocytoma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260317.txt"),
            quote = FALSE, sep = "\t", row.names = TRUE, col.names = TRUE)

# Write out the harmony seurat object.
saveRDS(astro_sobj_all_harmony_cleaned, paste0(out_data_dir, "/astrocytoma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260317.RDS"))
# astro_sobj_all_harmony_cleaned <- readRDS(paste0(out_data_dir, "/astrocytoma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260317.RDS"))

# Inspect some of the composition across samples.
sample_composition <- astro_sobj_all_harmony_cleaned@meta.data %>%
  group_by(SampleID, CellType_clusters, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(SampleID) %>%
  mutate(percentage = n / sum(n) * 100)

cell_type_colors <- c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", "Astrocyte" = "#BFBADA", 
                      "ExcNeuron" = "#BC80BD", "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", 
                      "Unresolved" = "gray70", "NA" = "black")

ggplot(sample_composition, aes(x = factor(SampleID), 
                                y = percentage, 
                                fill = CellType_clusters)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")
# This confirms what we observed in the original analysis, that NL26-1 was all malignant cells.
sample_composition %>% 
  filter(SampleID=="NL26-1")

#########################################################################################
##### Outputs for infercnv - astrocytoma
#########################################################################################
## We need to generate both counts and annotation files for these samples

### Create per-sample annotation files
sample_anno <- unique(astro_sobj_all_harmony_cleaned$SampleID)

##
# Open a file connection for writing
fileConn <- file("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/astrocytomas/astrocytoma_dataset_infercnv_samples.txt", "w")

# Write each element of the vector on a new line in the file
writeLines(sample_anno, fileConn)

# Close the file connection
close(fileConn)

processed_md <- astro_sobj_all_harmony_cleaned@meta.data
# There are 0 samples with less than 500 cells in total.
sum(table(processed_md$SampleID)<500)

Idents(astro_sobj_all_harmony_cleaned) <- "SampleID" 

## Generate a cell state specific annotation file for each sample.
for (i in 1:length(unique(sample_anno))) {
  
  print(sprintf("Analyzing sample: %s", sample_anno[i]))
  
  # Extract count matrix
  seurat_obj_singlets_sub <- subset(astro_sobj_all_harmony_cleaned,  idents = sample_anno[i], invert = FALSE)
  counts_matrix = GetAssayData(seurat_obj_singlets_sub, slot="counts")
  
  # save the output table as an R object (faster and more size efficient)
  saveRDS(round(counts_matrix, digits=3), paste0("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/astrocytomas/", sample_anno[i], "_counts.RDS"))
  
  ## Filter to each sample.
  processed_md_sample = processed_md %>%
    mutate(V1 = rownames(processed_md),
           V2 = CellType_clusters) %>% 
    filter(SampleID == sample_anno[i])
  
  ## Identify cell types to remove (infercnv will error if only one cell for a cell type is present)
  cell_type_to_drop <- processed_md_sample %>% 
    group_by(V2) %>% 
    summarise(cell_counts = n()) %>% 
    filter(cell_counts < 5)
  
  processed_md_sample_filt <- processed_md_sample %>% 
    filter(!V2%in%cell_type_to_drop$V2)
  
  ## Rename the tumor cells to identify the cell state in infercnv.
  processed_md_sample_filt <- processed_md_sample_filt[ , c("V1", "V2")]
  
  ## Write formatted annotation table to file
  write.table(processed_md_sample_filt, 
              file = paste0("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/astrocytomas/", unique(sample_anno)[i],"_sample_annotation_file.txt"),
              quote = FALSE, sep = "\t", row.names = FALSE, col.names = FALSE)
}


### END ###