##################################
# 10x snRNAseq analysis of preprocessing approaches for CARE-IDH-mutant oligodendrogliomas
# Author: Kevin Johnson
# Date Updated: 2026.03.18
##################################

library(tidyverse)
library(RColorBrewer)
library(viridis)
library(Seurat)
library(harmony)
library(Matrix)
library(ggpubr)
library(openxlsx)
library(DoubletFinder)

## Specify directories that have the count matrices. These are spread out across a few directories because they were processed at different times or by different labs.
in_data_dir_1 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/internal/batch1"
in_data_dir_2 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/internal/batch2"
in_data_dir_3 <- "/vast/palmer/pi/verhaak/kcj28/care_mut/data/counts/external"

# Define where figures and results will be stored
fig_dir <- "/vast/palmer/pi/verhaak/kcj28/care_mut/results/figures/rna/"
out_data_dir <- "/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna"
setwd("/vast/palmer/pi/verhaak/kcj28/care_mut/results/")

# Load in the master mapping file to utilize the different sample identifiers from the verhaak lab's data
map_df <- read.table("/vast/palmer/pi/verhaak/shared/monitor/metadata/glass_sn_bulk_master_mapping_file_20230729.txt", sep = "\t", header = T)
# Data generated by other groups (Suva + Iavarone labs)
map_df_external <- read.table("/vast/palmer/pi/verhaak/kcj28/care_mut/data/metadata/care_mut_external_dna_sn_linker_20230718.txt", sep = "\t", header = T)
map_df_external <- map_df_external %>% 
  mutate(file_path = ifelse(processed_by=="Iavarone lab", paste0("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/", avishay_id),
                            paste0("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/", data_name))) %>% 
  mutate(dir_name = ifelse(processed_by=="Iavarone lab",avishay_id, data_name))
# Needed to change this value since the data was coded differently for the directory versus metadata sheet.
map_df_external$dir_name[map_df_external$avishay_id=="P44T1"] <- "N1204557493"

# Are all files accounted for? Yes.
care_mut_dirs <- list.files("/vast/palmer/pi/verhaak/kcj28/care/data/counts/CAREmut/")
sum(map_df_external$dir_name%in%care_mut_dirs)
# This should be empty
map_df_external %>% 
  filter(!dir_name%in%care_mut_dirs)

# Restrict this analysis to IDHmut samples generated by our own lab - 23 patients, 51 samples. 5 samples with 3 time points.
map_df_mut <- map_df %>% 
  filter(idh_codel_subtype!="IDHwt") %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  mutate(patient_id = sapply(strsplit(multiome_id, "-|_"), "[[", 1))

# Create metadata file that is standard across patients
map_df_mut_filt <- map_df_mut %>% 
  mutate(lab = "Verhaak lab") %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  dplyr::select(SampleID = multiome_id, sample_barcode, case_barcode, lab, idh_codel_subtype)

map_df_external_filt <- map_df_external %>% 
  # Manually add the subtype status to the external datasets since all external sampes are IDHmut-noncodels
  mutate(idh_codel_subtype = "IDHmut-noncodel") %>% 
  mutate(sample_barcode = substr(aliquot_barcode, 1, 15)) %>% 
  mutate(case_barcode = substr(sample_barcode, 1, 12)) %>% 
  dplyr::select(SampleID = dir_name, sample_barcode, case_barcode, lab = processed_by, idh_codel_subtype)

md_to_add <- bind_rows(map_df_mut_filt, map_df_external_filt)

#########################################################################################
##### Load in the 10x data on which cells were filtered and DoubletFinder was run independently on each sample
#########################################################################################
seurat_obj_singlets <- readRDS("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/caremut_seuratobj_filt_singlets_20230728.RDS")

# Identify columns starting with "pANN" in the metadata and remove them for cleaning purposes. These were added by DoubletFinder.
# 342,244 total cells were initially left in the dataset
columns_to_remove <- grep("^pANN", colnames(seurat_obj_singlets@meta.data), value = TRUE)
seurat_obj_singlets@meta.data <- seurat_obj_singlets@meta.data[, !colnames(seurat_obj_singlets@meta.data) %in% columns_to_remove]

# Use a list of differentially expressed genes for IDHwt glioma (snRNA) so that we can later score cells, but restrict to the genes in this dataset.
celltype_markers <- readRDS("/vast/palmer/pi/verhaak/kcj28/genelists/celltype_markers.RDS")

# Select the top 100 genes in terms of fold-change for each cell type.
selected_genes <- celltype_markers %>%
  filter(CellType %in% c("Malignant", "Astrocyte", "Excitatory neuron", "Inhibitory neuron", "OPC", "Oligodendrocyte", "Endothel", "Pericyte", "Macrophage", "Tcell", "Bcell")) %>%
  group_by(CellType) %>%
  arrange(CellType, desc(log2FC)) %>%
  top_n(100, log2FC)

all.genes <- rownames(seurat_obj_singlets)
selected_genes_vector <- unique(selected_genes$Gene[selected_genes$Gene%in%all.genes])
# Check to make sure that each gene is only being used once as some marker genes overlap.
n_distinct(selected_genes_vector)==length(selected_genes_vector)

# Conver this to a list so that we can later use Seurat's AddModuleScore
selected_genes_filt <- selected_genes %>% 
  filter(Gene%in%selected_genes_vector, !CellType%in%c("Unresolved", "Other normal")) %>% 
  as.data.frame()
cell_type_markers <- split(selected_genes_filt, selected_genes_filt$CellType)
cell_type_markers_list <- lapply(cell_type_markers, function(x) as.character(x$Gene))

# Determine the length of each element in the list
lengths <- lengths(cell_type_markers_list)

# Subset the list to exclude elements with length 0. These are the marker genes from IDH-wildtype tumors snRNA data from the CARE consortium, which may make it easier to
# identify suspicious populations or potentially ambiguous clusters based on prior knowledge.
cell_type_markers_list <- cell_type_markers_list[lengths > 0]

# Add the metadata of case_barcode and processing_lab - if desired.
seurat_md <- seurat_obj_singlets@meta.data
seurat_md$CellID <- rownames(seurat_md)
add_data <- seurat_md %>% 
  left_join(md_to_add, by="SampleID")

# Sanity check
all(rownames(seurat_md)==row.names(seurat_obj_singlets[[]]))
rownames(seurat_md)==row.names(seurat_obj_singlets[[]])
all(add_data$CellID==row.names(seurat_obj_singlets[[]]))

row.names(add_data) <- row.names(seurat_obj_singlets[[]])

seurat_obj_singlets <- AddMetaData(seurat_obj_singlets, metadata = add_data)
# seurat_obj_singlets$CellID <- rownames(seurat_obj_singlets@meta.data)
all(seurat_obj_singlets$CellID==rownames(seurat_obj_singlets@meta.data))

# Load in th final metadata that was used in the paper and in downstream analyses.
caremut_md <- read.table("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/care_mut_cleaned_snrna_metadata_n75_20240212.txt", sep = "\t", row.names = 1, header = TRUE)
caremut_md_filtered <- caremut_md %>% 
  dplyr::select(CellID, CellType_initial_og = CellType_initial, CellType_infercnv_og = CellType_infercnv, CellType_final_og = CellType_final,
                predicted.class, predicted.subclass, scna_burden, malignant_cor, care_id, sample_barcode)
seurat_md_part2 <- seurat_obj_singlets@meta.data

add_data_part2 <- seurat_md_part2 %>% 
  left_join(caremut_md_filtered, by="CellID")
all(add_data_part2$CellID==row.names(seurat_obj_singlets[[]]))
add_data_part2$CellID==row.names(seurat_obj_singlets[[]])

row.names(add_data_part2) <- row.names(seurat_obj_singlets[[]])

seurat_obj_singlets <- AddMetaData(seurat_obj_singlets, metadata = add_data_part2)

all(rownames(seurat_obj_singlets@meta.data)==Cells(seurat_obj_singlets))

#########################################################################################
##### Preprocess with Harmony - codel
#########################################################################################
# Subset the data to only those codel/oligodendroglioma tumors
seurat_obj_singlets_codel <- subset(seurat_obj_singlets, idh_codel_subtype=="IDHmut-codel")
rm(seurat_obj_singlets)
gc()

# There are 30 distinct tumors (All processed by the Verhaak lab)
n_distinct(seurat_obj_singlets_codel$SampleID)
table(seurat_obj_singlets_codel$SampleID, seurat_obj_singlets_codel$lab)


# First, run through a standard Seurat workflow. This might be acceptable because there was only one batch here.
oligo_sobj_all <- NormalizeData(seurat_obj_singlets_codel, normalization.method = "LogNormalize", scale.factor = 10000)
oligo_sobj_all <- FindVariableFeatures(oligo_sobj_all, selection.method = "vst", nfeatures = 5000)
# By default only variable features are scaled. That should acceptable here.
oligo_sobj_all <- ScaleData(oligo_sobj_all)
oligo_sobj_all <- RunPCA(oligo_sobj_all, features = VariableFeatures(object = oligo_sobj_all), npcs=50)
oligo_sobj_all <- FindNeighbors(oligo_sobj_all, dims = 1:20) 
oligo_sobj_all <- FindClusters(oligo_sobj_all, resolution = 0.6) 
oligo_sobj_all <- RunUMAP(oligo_sobj_all, dims = 1:20, min.dist = 0.2, n.neighbors = 40)


options(ggrepel.max.overlaps = Inf)
# Visualize a few of the results:
DimPlot(oligo_sobj_all, label = TRUE, group.by = "RNA_snn_res.0.6",repel = TRUE,  pt.size = 1) 
DimPlot(oligo_sobj_all, label = TRUE, group.by = "CellType_final_og",repel = TRUE,  pt.size = 1) 
DimPlot(oligo_sobj_all, label = TRUE, group.by = "predicted.subclass",repel = TRUE,  pt.size = 1) 
DimPlot(oligo_sobj_all, label = TRUE, group.by = "CellType_initial_og",repel = TRUE,  pt.size = 1) 

DimPlot(oligo_sobj_all, label = TRUE, group.by = "case_barcode", repel = TRUE,  pt.size = 1) 

# Create a version that represents the standard preprocessing.
standard_umap_plot <- DimPlot(oligo_sobj_all, group.by = "CellType_final_og",
                              cols =  c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", 
                                        "Astrocyte" = "#BFBADA", "ExcNeuron" = "#BC80BD", 
                                        "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", "Unresolved" = "gray70"),
                              # Manually add point size for larger number of cells
                              pt.size = 1) + ggtitle("No Harmony batch correction")
patient_standard_umap_plot <- DimPlot(oligo_sobj_all, label = TRUE, group.by = "case_barcode", repel = TRUE,  pt.size = 1) 
ggsave(paste0(fig_dir, "oligodendroglioma_standard_processing_umap_20260315.png"), standard_umap_plot, width = 7, height = 4, dpi = 300)
ggsave(paste0(fig_dir, "oligodendroglioma_standard_processing_patient_umap_20260315.png"), patient_standard_umap_plot, width = 7, height = 4, dpi = 300)




### Harmony batch correction similar to what was used in the paper with set.seed(1)
oligo_sobj_all_harmony <- NormalizeData(seurat_obj_singlets_codel, normalization.method = "LogNormalize", scale.factor = 10000)
oligo_sobj_all_harmony <- FindVariableFeatures(oligo_sobj_all_harmony, selection.method = "vst", nfeatures = 5000)
# By default only variable features are scaled
oligo_sobj_all_harmony <- ScaleData(oligo_sobj_all_harmony)
#  default: seed.use = 42 
oligo_sobj_all_harmony <- RunPCA(oligo_sobj_all_harmony, features = VariableFeatures(object = oligo_sobj_all_harmony), npcs=50)
set.seed(1)
oligo_sobj_all_harmony <- RunHarmony(oligo_sobj_all_harmony, group.by.vars = c("case_barcode"), dims.use = 1:30)
oligo_sobj_all_harmony <- FindNeighbors(oligo_sobj_all_harmony, reduction = "harmony", dims = 1:20) 
# default: random.seed = 0
oligo_sobj_all_harmony <- FindClusters(oligo_sobj_all_harmony, resolution = 0.6) 
#  default: seed.use = 42 
oligo_sobj_all_harmony <- RunUMAP(oligo_sobj_all_harmony, reduction = "harmony", dims = 1:20, min.dist = 0.2, n.neighbors = 40)


# Harmony defined clusters
DimPlot(oligo_sobj_all_harmony, label = TRUE, group.by = "RNA_snn_res.0.6",repel = TRUE,  pt.size = 1) 


# Create a version that represents the Harmony pre-processing with set.seed(1)
harmony_umap_plot <- DimPlot(oligo_sobj_all_harmony, group.by = "CellType_final_og",
                              cols =  c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", 
                                        "Astrocyte" = "#BFBADA", "ExcNeuron" = "#BC80BD", 
                                        "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", "Unresolved" = "gray70"),
                              # Manually add point size for larger number of cells
                              pt.size = 1) + ggtitle("Harmony - set.seed(42)")
patient_harmony_umap_plot <- DimPlot(oligo_sobj_all_harmony, label = TRUE, group.by = "case_barcode", repel = TRUE,  pt.size = 1) 
ggsave(paste0(fig_dir, "oligodendroglioma_harmony_seed1_umap_20260318.png"), harmony_umap_plot, width = 7, height = 4, dpi = 300)
ggsave(paste0(fig_dir, "oligodendroglioma_harmony_seed1_patient_umap_20260318.png"), patient_harmony_umap_plot, width = 7, height = 4, dpi = 300)


# We defined a set of cell type marker genes from IDH-WT glioblastoma (above). Score each cell for these signatures to help identify clusters in this dataset.
oligo_sobj_all_harmony <- AddModuleScore(oligo_sobj_all_harmony,
                                         features = cell_type_markers_list,
                                         name=names(cell_type_markers_list))

sig_cols <- c("Malignant1", "Oligodendrocyte2", "Macrophage3", "Astrocyte4", 
              "Excitatory.neuron5", "Inhibitory.neuron6", "Endothel7", 
              "Pericyte8", "Tcell9", "Bcell10", "OPC11")
oligo_sobj_all_harmony@meta.data <- oligo_sobj_all_harmony@meta.data %>%
  rename_with(~ sub("\\d+$", "_sig", .x), all_of(sig_cols))

sig_cols_added <- c("Malignant_sig", "Oligodendrocyte_sig", "Macrophage_sig", 
                    "Astrocyte_sig", "Excitatory.neuron_sig", "Inhibitory.neuron_sig", 
                    "Endothel_sig", "Pericyte_sig", "Tcell_sig", "Bcell_sig", "OPC_sig")


# Find the column name with the highest score per cell. These align with what's expected.
oligo_sobj_all_harmony@meta.data <- oligo_sobj_all_harmony@meta.data %>%
  mutate(CellType_Sig = apply(across(all_of(sig_cols_added)), 1, function(x) {
    sig_cols_added[which.max(x)]
  }))
DimPlot(oligo_sobj_all_harmony, label = TRUE, group.by = "CellType_Sig",repel = TRUE,  pt.size = 1) 

# Plot these individual signatures to identify any potential residual doublet populations.
# Malignant+Macrophage+Oligodendrocyte are the most abundant and DoubletFinder doesn't capture these populations very well.
FeaturePlot(oligo_sobj_all_harmony,  features = "Malignant_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Oligodendrocyte_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Macrophage_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Astrocyte_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Excitatory.neuron_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Inhibitory.neuron_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Endothel_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Pericyte_sig",  pt.size = 1) 
# Lymphocyte signal
FeaturePlot(oligo_sobj_all_harmony,  features = "Tcell_sig",  pt.size = 1) 
FeaturePlot(oligo_sobj_all_harmony,  features = "Bcell_sig",  pt.size = 1) 


# Get a feeling for which clusters may be problematic and save
cells_per_cluster <- oligo_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, .drop = FALSE) %>% 
  summarise(counts = n()) %>% 
  ungroup()

cluster_composition_sample <- oligo_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, sample_barcode, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

high_percentage_clusters <- cluster_composition_sample %>% 
  filter(percentage > 50)

# Examine the cluster composition based on our first pass classification
cluster_composition <- oligo_sobj_all_harmony@meta.data %>%
  mutate(CellType_final_og = as.character(CellType_final_og)) %>%  # ensure NAs aren't dropped as factor levels
  group_by(RNA_snn_res.0.6, CellType_final_og, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

cell_type_colors <- c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", "Astrocyte" = "#BFBADA", 
                      "ExcNeuron" = "#BC80BD", "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", 
                      "Unresolved" = "gray70", "NA" = "black")

ggplot(cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                y = percentage, 
                                fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

ggplot(cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                y = n, 
                                fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")


# It seems like the main clusters to drop are C18, C14, and C17. Subcluster C16 and C17.
# Examine the clusters by SampleIDs.
suspicious_clusters_by_sample_freq <- oligo_sobj_all_harmony@meta.data %>%
  group_by(RNA_snn_res.0.6, SampleID) %>% 
  summarise(counts = n()) %>% 
  mutate(freq = counts / sum(counts)) %>% 
  ungroup() %>% 
  filter(RNA_snn_res.0.6%in%c("14", "16", "17", "18"))

c16 <- oligo_sobj_all_harmony@meta.data %>%
  filter(RNA_snn_res.0.6%in%c("16")) 
table(c16$CellType_final_og)

# Oligodendrocyte+Malignant residual doublets
DimPlot(oligo_sobj_all_harmony, cells.highlight = WhichCells(oligo_sobj_all_harmony, idents = "14"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
# Mostly mural cells but a subcluster of residual doublets
DimPlot(oligo_sobj_all_harmony, cells.highlight = WhichCells(oligo_sobj_all_harmony, idents = "16"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
# Myeloid+Malignant residual doublets
DimPlot(oligo_sobj_all_harmony, cells.highlight = WhichCells(oligo_sobj_all_harmony, idents = "17"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)
# Myeloid+Oligodendrocyte residual doublets
DimPlot(oligo_sobj_all_harmony, cells.highlight = WhichCells(oligo_sobj_all_harmony, idents = "18"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)

# C30 is quite spread out across the UMAP. Perform sub-clustering
oligo_sobj_all_harmony <- FindSubCluster(oligo_sobj_all_harmony,
                                                       "16",
                                                       graph.name = "RNA_nn",
                                                       subcluster.name = "seurat_final_clusters",
                                                       resolution = 0.1,
                                                       algorithm = 1
)


DimPlot(oligo_sobj_all_harmony, label = TRUE, group.by = "seurat_final_clusters",repel = TRUE,  pt.size = 1) 

Idents(oligo_sobj_all_harmony) <- "seurat_final_clusters"
DimPlot(oligo_sobj_all_harmony, cells.highlight = WhichCells(oligo_sobj_all_harmony, idents = "16_1"), cols.highlight = "red", cols = "lightgrey", pt.size = 1, raster = FALSE)

# Where do these residual doublets map on the UMAP:
potential_doublets <- rownames(oligo_sobj_all_harmony@meta.data)[oligo_sobj_all_harmony@meta.data$seurat_final_clusters%in%c("14", "16_1", "17", "18")]
DimPlot(oligo_sobj_all_harmony, label=T, cells.highlight = list(potential_doublets), cols.highlight = c("darkblue"), cols= "grey", pt.size = 1,  raster = FALSE)


pre_removal_cell_num <- dim(oligo_sobj_all_harmony)[2]
# C14 = Oligodendrocyte+Malignant residual doublets
# C16_1 = Mural+Oligodendrocyte residual doublets
# C17 = Macrophage+Oligodendrocyte C18 = Macrophage+Malignant residual doublets.
# Remove residual doublets:
oligo_sobj_all_harmony_cleaned <- subset(oligo_sobj_all_harmony, idents = c("14", "16_1", "17", "18"), invert = TRUE)
dropped_cells <- pre_removal_cell_num-dim(oligo_sobj_all_harmony_cleaned)[2]
sprintf("%s cells were removed due to ambiguous clusters.", dropped_cells) # 4,074 cells 

# Plot cleaned UMAP
DimPlot(oligo_sobj_all_harmony_cleaned, label = TRUE, repel = TRUE, pt.size = 1) + NoLegend()


clean_cluster_composition <- oligo_sobj_all_harmony_cleaned@meta.data %>%
  mutate(CellType_final_og = as.character(CellType_final_og)) %>%  # ensure NAs aren't dropped as factor levels
  group_by(RNA_snn_res.0.6, CellType_final_og, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(RNA_snn_res.0.6) %>%
  mutate(percentage = n / sum(n) * 100)

ggplot(clean_cluster_composition, aes(x = factor(RNA_snn_res.0.6), 
                                      y = percentage, 
                                      fill = CellType_final_og)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")


# Provide a celltype assignment based on these initial 
oligo_sobj_all_harmony_cleaned$CellType_clusters <- paste0("C", as.character(oligo_sobj_all_harmony_cleaned$seurat_final_clusters))
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C1", "C3", "C24"), "Oligodendrocyte", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C5", "C25"),"Myeloid", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C21"),"Lymphocyte", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C7"),"ExcNeuron", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C8"),"InhNeuron", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C16_0"),"Mural", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C15"),"Endothelial", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C11"),"Astrocyte", oligo_sobj_all_harmony_cleaned$CellType_clusters)
oligo_sobj_all_harmony_cleaned$CellType_clusters <- ifelse(oligo_sobj_all_harmony_cleaned$CellType_clusters %in% c("C0", "C2", "C4","C6","C9", "C10", "C12", "C13", "C19", "C20","C22", "C23"),"Malignant", oligo_sobj_all_harmony_cleaned$CellType_clusters)

png(paste0(fig_dir, "caremut_snrna_post_dfinder_cleaned_umap_celltype_oligodendroglioma_20260318.png"), width=10, height=8, res=300, units='in')
DimPlot(oligo_sobj_all_harmony_cleaned, group.by = "CellType_clusters", label = TRUE, repel = TRUE, 
        cols =  c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", 
                  "Astrocyte" = "#BFBADA", "ExcNeuron" = "#BC80BD", 
                  "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7"),
        pt.size = 1) +
  labs(x="UMAP1", y="UMAP2",color="Cell type")
dev.off()

table(oligo_sobj_all_harmony_cleaned$CellType_initial_og, oligo_sobj_all_harmony_cleaned$CellType_clusters)
table(oligo_sobj_all_harmony_cleaned$CellType_final_og, oligo_sobj_all_harmony_cleaned$CellType_clusters)

# Approximate match percentage across gene expression clusters (99.4%).
sum(oligo_sobj_all_harmony_cleaned$CellType_initial_og==oligo_sobj_all_harmony_cleaned$CellType_clusters, na.rm = TRUE)/length(oligo_sobj_all_harmony_cleaned$CellType_clusters)

# Examine the mismatch in expression profiles.
expression_mismatch <- oligo_sobj_all_harmony_cleaned@meta.data %>% 
  filter(CellType_initial_og!=CellType_clusters) %>% 
  dplyr::select(SampleID, sample_barcode, CellType_initial_og, CellType_clusters, CellType_final_og, seurat_final_clusters)

table(expression_mismatch$CellType_final_og, expression_mismatch$CellType_clusters)
expression_mismatch %>% filter(CellType_clusters=="Myeloid" | CellType_initial_og=="Myeloid")


#########################################################################################
######### Write out CARE-mut metadata file containing cell state identifier
#########################################################################################
# Set the metadata and create a CellID
caremut_md_out <- oligo_sobj_all_harmony_cleaned@meta.data

# Write out metadata table
write.table(caremut_md_out, 
            file = paste0(out_data_dir, "/oligodendroglioma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260318.txt"),
            quote = FALSE, sep = "\t", row.names = TRUE, col.names = TRUE)

# Write out the harmony seurat object.
saveRDS(oligo_sobj_all_harmony_cleaned, paste0(out_data_dir, "/oligodendroglioma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260318.RDS"))
# oligo_sobj_all_harmony_cleaned <- readRDS(paste0(out_data_dir, "/oligodendroglioma_seuratobj_filt_singlets_cleaned_mdata_celltype_annotated_20260318.RDS"))

# Inspect some of the composition across samples.
sample_composition <- oligo_sobj_all_harmony_cleaned@meta.data %>%
  group_by(SampleID, CellType_clusters, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(SampleID) %>%
  mutate(percentage = n / sum(n) * 100)

cell_type_colors <- c("Malignant" = "#FB8072", "Oligodendrocyte" = "#B3DE69", "Myeloid" = "#80B1D3", "Astrocyte" = "#BFBADA", 
                      "ExcNeuron" = "#BC80BD", "InhNeuron" = "#FFED6F", "Endothelial" = "#FCCDE5", "Mural" = "#FFFFB3", "Lymphocyte" = "#8DD3C7", 
                      "Unresolved" = "gray70", "NA" = "black")

ggplot(sample_composition, aes(x = factor(SampleID), 
                               y = percentage, 
                               fill = CellType_clusters)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = cell_type_colors, na.value = "#D3D3D3") +
  labs(x = "Cluster", 
       y = "Percentage (%)", 
       fill = "Cell Type",
       title = "Cluster Composition by Cell Type") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

sample_composition %>% 
  filter(SampleID=="SJ02-3")

# This was a sample with low quality malignant cells in the first run. It's also the third sample and had low DNA purity.
poor_sample <- oligo_sobj_all_harmony_cleaned@meta.data %>% 
  filter(SampleID=="SJ02-3")
table(poor_sample$CellType_initial_og)

prior_composition <- caremut_md %>% 
  group_by(SampleID, CellType_final, .drop = FALSE) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(SampleID) %>%
  mutate(percentage = n / sum(n) * 100)

prior_composition_malignant <- prior_composition %>% 
  filter(CellType_final=="Malignant")

#########################################################################################
##### Outputs for infercnv - oligodendroglioma
#########################################################################################
## We need to generate both counts and annotation files for these samples

### Create per-sample annotation files
sample_anno <- unique(oligo_sobj_all_harmony_cleaned$SampleID)

##
# Open a file connection for writing
fileConn <- file("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/oligodendrogliomas/oligodendroglioma_dataset_infercnv_samples.txt", "w")

# Write each element of the vector on a new line in the file
writeLines(sample_anno, fileConn)

# Close the file connection
close(fileConn)

processed_md <- oligo_sobj_all_harmony_cleaned@meta.data
# There are 0 samples with less than 500 cells in total.
sum(table(processed_md$SampleID)<500)

Idents(oligo_sobj_all_harmony_cleaned) <- "SampleID" 

## Generate a cell state specific annotation file for each sample.
for (i in 1:length(unique(sample_anno))) {
  
  print(sprintf("Analyzing sample: %s", sample_anno[i]))
  
  # Extract count matrix
  seurat_obj_singlets_sub <- subset(oligo_sobj_all_harmony_cleaned,  idents = sample_anno[i], invert = FALSE)
  counts_matrix = GetAssayData(seurat_obj_singlets_sub, slot="counts")
  
  # save the output table as an R object (faster and more size efficient)
  saveRDS(round(counts_matrix, digits=3), paste0("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/oligodendrogliomas/", sample_anno[i], "_counts.RDS"))
  
  ## Filter to each sample.
  processed_md_sample = processed_md %>%
    mutate(V1 = rownames(processed_md),
           V2 = CellType_clusters) %>% 
    filter(SampleID == sample_anno[i])
  
  ## Identify cell types to remove (infercnv will error if only one cell for a cell type is present)
  cell_type_to_drop <- processed_md_sample %>% 
    group_by(V2) %>% 
    summarise(cell_counts = n()) %>% 
    filter(cell_counts < 5)
  
  processed_md_sample_filt <- processed_md_sample %>% 
    filter(!V2%in%cell_type_to_drop$V2)
  
  ## Rename the tumor cells to identify the cell state in infercnv.
  processed_md_sample_filt <- processed_md_sample_filt[ , c("V1", "V2")]
  
  ## Write formatted annotation table to file
  write.table(processed_md_sample_filt, 
              file = paste0("/vast/palmer/pi/verhaak/kcj28/care_mut/processed_data/rna/infercnv_inputs/oligodendrogliomas/", unique(sample_anno)[i],"_sample_annotation_file.txt"),
              quote = FALSE, sep = "\t", row.names = FALSE, col.names = FALSE)
}


### END ###